CREATE DATABASE IF NOT EXISTS robot_arm
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE robot_arm;

CREATE TABLE IF NOT EXISTS armstate (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vacuum VARCHAR(255) NOT NULL DEFAULT 'off',
  auto_mode BOOLEAN NOT NULL DEFAULT FALSE,
  s0_deg INT NULL,
  s0_pwm INT NULL,
  s1_deg INT NULL,
  s1_pwm INT NULL,
  s2_deg INT NULL,
  s2_pwm INT NULL,
  s3_deg INT NULL,
  s3_pwm INT NULL,
  raw_data TEXT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS vacuumlog (
  id INT AUTO_INCREMENT PRIMARY KEY,
  action VARCHAR(255) NOT NULL DEFAULT 'off',
  triggered_by VARCHAR(255) NOT NULL DEFAULT 'ws',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS commandlog (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(255) NOT NULL DEFAULT 'api',
  command VARCHAR(255) NOT NULL DEFAULT '',
  payload TEXT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS vehiclestate (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pitch FLOAT NULL,
  roll FLOAT NULL,
  cur_a INT NULL,
  cur_b INT NULL,
  cur_c INT NULL,
  cur_d INT NULL,
  cur_e INT NULL,
  is_balanced BOOLEAN NOT NULL DEFAULT FALSE,
  raw_data TEXT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
